#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

engine=npm
yarn --version &> /dev/null
if [ $? -eq 0 ]; then
  engine=yarn
fi

if [[ -n $(git status -s) ]]; then
    echo "Working directory is not empty, commit or stash changes before pushing."
    echo "Use option `--no-verify` to skip this check"
    exit 1
fi
"$engine" install --check-files
"$engine" format
"$engine" lint --fix
if [[ -n $(git status -s) ]]; then
    git add -A
    git commit -m "Husky: Committing result of prettier"
fi
